### ISSUE TITLE
Setup CI and coverage

### ISSUE THREAD

**Issue by MaximeBouton** [sisl/AutomotiveInteraction.jl#4]
It would be nice to have travis and coveralls enabled for this package.

**Comment by raunakbh92** [comment]
Travis-CI and Coveralls seems to work. However, Documenter is not creating `gh-pages` branch, and hence documentation is not showing up from the docs badge link. Do I need to manually create a page using github pages? I assumed that SISL will have a `sisl.github.io` repo.

**Comment by MaximeBouton** [comment]
everything should be created automatically during the travis build

**Comment by MaximeBouton** [comment]
I think I know where it is coming from: 
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Travis-CI-1

See the note about the matrix section in travis. 
(just remove the matrix section from .travis.yml and that should do it)

**Comment by raunakbh92** [comment]
Seems to fail. In fact, this was the first time the documentation build even got triggered on Travis-CI so that is a good thing. Here is the failure [job log](https://travis-ci.org/github/sisl/AutomotiveInteraction.jl/jobs/661298048). Looks like an issue with adding `AutomotiveInteraction` when trying to add `Documenter`.

**Comment by MaximeBouton** [comment]
Here: https://github.com/sisl/AutomotiveInteraction.jl/blob/master/docs/Project.toml#L2
you don't want AutomotiveInteraction, since it is not registered anywhere, it complains when doing version checks when you try to add AutomotiveInteraction again.

You might want to have Documenter in the deps.

**Comment by raunakbh92** [comment]
Docs are now showing up from the badge on the readme.
